(()=>{'use strict';
const URL='https://yfqadqjgkvrgjiukdnck.supabase.co';
const KEY='sb_publishable_244hp9IeSY1TScbGTTr9vw_fHdd1MC3';
const CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
const cloud={client:null,session:null,ready:false,syncing:false,saveTimer:null,originalSave:null};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const say=m=>{try{typeof toast==='function'?toast(m):console.log('[ZORYVO]',m)}catch{console.log('[ZORYVO]',m)}};
const render=()=>{try{typeof renderAll==='function'&&renderAll()}catch(e){console.warn(e)}};
function style(){if(q('#zCloudStyle'))return;const s=document.createElement('style');s.id='zCloudStyle';s.textContent='.z-cloud{margin-top:12px;padding:13px;border:1px solid rgba(35,165,255,.22);border-radius:18px;background:#08131f}.z-cloud h3{margin:0;font-size:12px}.z-cloud p{margin:4px 0 10px;color:#8fa0b5;font-size:8px;line-height:1.4}.z-cloud input{width:100%;height:40px;margin:4px 0;border-radius:12px;border:1px solid #223044;background:#07101a;color:#fff;padding:0 11px}.z-cloud-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:6px}.z-cloud button{height:38px;border:0;border-radius:12px;font-weight:900}.z-cloud .pri{background:linear-gradient(135deg,#18d8ff,#62eaff);color:#031017}.z-cloud .sec{background:#111a27;color:#dce6f5;border:1px solid #263347}.z-cloud-status{margin-top:8px;font-size:8px;color:#91a2b6}.z-cloud-status.ok{color:#74e9b7}.z-cloud-status.err{color:#ff9daf}.z-cloud-user{display:none}.z-cloud-user.show{display:flex;align-items:center;justify-content:space-between;gap:8px}.z-cloud-user span{font-size:8px;color:#9dacbe;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:520px){.z-cloud-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function status(m,c=''){const e=q('#zCloudStatus');if(e){e.textContent=m;e.className='z-cloud-status '+c}}
function card(){if(q('#zCloud'))return;const host=q('#view-profile .profile')||q('.profile');if(!host)return;const e=document.createElement('section');e.id='zCloud';e.className='z-cloud';e.innerHTML='<h3>Cuenta ZORYVO Cloud</h3><p>Sincroniza saldo, biblioteca, progreso y recompensas con Supabase.</p><div id="zCloudForm"><input id="zCloudEmail" type="email" autocomplete="email" placeholder="Correo electrónico"><input id="zCloudPass" type="password" autocomplete="current-password" placeholder="Contraseña (mínimo 6 caracteres)"><div class="z-cloud-actions"><button class="pri" id="zCloudLogin" type="button">Iniciar sesión</button><button class="sec" id="zCloudRegister" type="button">Crear cuenta</button></div></div><div class="z-cloud-user" id="zCloudUser"><span id="zCloudUserEmail"></span><button class="sec" id="zCloudLogout" type="button">Salir</button></div><div class="z-cloud-status" id="zCloudStatus">Inicializando conexión…</div>';host.appendChild(e);q('#zCloudLogin').onclick=login;q('#zCloudRegister').onclick=register;q('#zCloudLogout').onclick=logout}
function authUI(){const on=!!cloud.session?.user;const f=q('#zCloudForm'),u=q('#zCloudUser'),em=q('#zCloudUserEmail');if(f)f.style.display=on?'none':'block';if(u)u.classList.toggle('show',on);if(em)em.textContent=cloud.session?.user?.email||cloud.session?.user?.id||'';status(on?'Conectado y sincronizado con Supabase.':'Modo local. Inicia sesión para activar la nube.',on?'ok':'')}
function lib(){return new Promise((res,rej)=>{if(window.supabase?.createClient)return res();const s=document.createElement('script');s.src=CDN;s.onload=res;s.onerror=()=>rej(new Error('No se pudo cargar Supabase JS'));document.head.appendChild(s)})}
function creds(){return{email:(q('#zCloudEmail')?.value||'').trim(),password:q('#zCloudPass')?.value||''}}
async function login(){const c=creds();if(!c.email||c.password.length<6)return status('Correo o contraseña inválidos.','err');status('Iniciando sesión…');const{data,error}=await cloud.client.auth.signInWithPassword(c);if(error)return status(error.message,'err');cloud.session=data.session;authUI();await sync(true)}
async function register(){const c=creds();if(!c.email||c.password.length<6)return status('Correo o contraseña inválidos.','err');status('Creando cuenta…');const{data,error}=await cloud.client.auth.signUp({email:c.email,password:c.password,options:{data:{display_name:'Usuario ZORYVO'}}});if(error)return status(error.message,'err');if(!data.session)return status('Cuenta creada. Confirma tu correo y luego inicia sesión.','ok');cloud.session=data.session;authUI();await sync(true)}
async function logout(){await cloud.client.auth.signOut();cloud.session=null;authUI();say('Sesión de nube cerrada')}
function prefs(){return{settings:state?.settings||{},likes:state?.likes||[],history:state?.history||[],interactive:state?.interactive||{},notificationsRead:state?.notificationsRead||[],vip:!!state?.vip}}
async function push(){if(!cloud.session?.user||cloud.syncing||typeof state==='undefined')return;cloud.syncing=true;try{const uid=cloud.session.user.id;const rr=await cloud.client.from('library').select('series_id').eq('user_id',uid);if(rr.error)throw rr.error;const local=new Set(state.library||[]),remote=new Set((rr.data||[]).map(x=>x.series_id));const add=[...local].filter(x=>!remote.has(x)).map(series_id=>({user_id:uid,series_id}));if(add.length)await cloud.client.from('library').upsert(add,{onConflict:'user_id,series_id'});for(const id of [...remote].filter(x=>!local.has(x)))await cloud.client.from('library').delete().eq('user_id',uid).eq('series_id',id);const pro=Object.entries(state.progress||{}).map(([series_id,p])=>({user_id:uid,series_id,episode_id:String(p.ep||1),progress_seconds:Number(p.time)||0,duration_seconds:Number(p.duration)||0,completed:(Number(p.percent)||0)>=99}));if(pro.length)await cloud.client.from('progress').upsert(pro,{onConflict:'user_id,series_id,episode_id'});await cloud.client.from('user_preferences').upsert({user_id:uid,data:prefs()},{onConflict:'user_id'});status('Cambios sincronizados.','ok')}catch(e){console.warn(e);status('Guardado localmente; sincronización pendiente.','err')}finally{cloud.syncing=false}}
function queue(){if(!cloud.session?.user)return;clearTimeout(cloud.saveTimer);cloud.saveTimer=setTimeout(push,900)}
async function snapshot(){const uid=cloud.session.user.id;const[a,b,c,d,e,f]=await Promise.all([cloud.client.from('user_state').select('coins,passes,streak,last_daily').eq('user_id',uid).single(),cloud.client.from('library').select('series_id').eq('user_id',uid),cloud.client.from('progress').select('series_id,episode_id,progress_seconds,duration_seconds,completed,updated_at').eq('user_id',uid),cloud.client.from('unlocks').select('series_id,episode').eq('user_id',uid),cloud.client.from('user_preferences').select('data').eq('user_id',uid).maybeSingle(),cloud.client.from('reward_claims').select('reward_type,reward_key').eq('user_id',uid)]);const er=a.error||b.error||c.error||d.error||e.error||f.error;if(er)throw er;return{eco:a.data,lib:b.data||[],pro:c.data||[],un:d.data||[],pref:e.data?.data||{},claims:f.data||[]}}
function apply(s){if(typeof state==='undefined')return;state.coins=Number(s.eco?.coins)||0;state.freePasses=Number(s.eco?.passes)||0;state.reward=state.reward||{};state.reward.streak=Number(s.eco?.streak)||0;state.reward.lastClaim=s.eco?.last_daily||null;state.library=[...new Set(s.lib.map(x=>x.series_id))];state.progress={};state.completedEpisodes=[];for(const r of s.pro){const ep=parseInt(String(r.episode_id).replace(/\D/g,''),10)||1;state.progress[r.series_id]={ep,time:Number(r.progress_seconds)||0,duration:Number(r.duration_seconds)||0,percent:r.completed?100:(Number(r.duration_seconds)>0?(Number(r.progress_seconds)/Number(r.duration_seconds))*100:0),updatedAt:Date.parse(r.updated_at)||Date.now()};if(r.completed)state.completedEpisodes.push(r.series_id+':'+ep)}const un={};for(const r of s.un)(un[r.series_id]??=[]).push(Number(r.episode));for(const[k,v]of Object.entries(state.unlocked||{}))un[k]=[...new Set([...(un[k]||[]),...v])].sort((x,y)=>x-y);state.unlocked=un;if(s.pref.settings)state.settings={...(state.settings||{}),...s.pref.settings};if(Array.isArray(s.pref.likes))state.likes=s.pref.likes;if(Array.isArray(s.pref.history))state.history=s.pref.history;if(s.pref.interactive)state.interactive=s.pref.interactive;if(Array.isArray(s.pref.notificationsRead))state.notificationsRead=s.pref.notificationsRead;if(typeof s.pref.vip==='boolean')state.vip=s.pref.vip;const cl=new Set(s.claims.map(x=>x.reward_type+':'+x.reward_key));state.reward.claimedTasks=state.reward.claimedTasks||[];if(cl.has('library:first_save')&&!state.reward.claimedTasks.includes('library'))state.reward.claimedTasks.push('library');if(cl.has('three_episodes:first_three')&&!state.reward.claimedTasks.includes('watch3'))state.reward.claimedTasks.push('watch3');try{cloud.originalSave?.()}catch{}render()}
async function sync(migrate=false){if(!cloud.session?.user||cloud.syncing)return;cloud.syncing=true;try{if(migrate)await push();const s=await snapshot();apply(s);status('Sincronización completa.','ok')}catch(e){console.error(e);status('No se pudo sincronizar ahora. ZORYVO seguirá en modo local.','err')}finally{cloud.syncing=false}}
async function economy(){const uid=cloud.session.user.id;const{data,error}=await cloud.client.from('user_state').select('coins,passes,streak,last_daily').eq('user_id',uid).single();if(error)throw error;state.coins=Number(data.coins)||0;state.freePasses=Number(data.passes)||0;state.reward.streak=Number(data.streak)||0;state.reward.lastClaim=data.last_daily||null;try{cloud.originalSave?.()}catch{}render()}
function hooks(){if(typeof saveState==='function'&&!cloud.originalSave){cloud.originalSave=saveState;window.saveState=function(...a){const r=cloud.originalSave.apply(this,a);queue();return r}}q('#video')?.addEventListener('ended',async()=>{if(!cloud.session?.user||typeof runtime==='undefined')return;try{await cloud.client.rpc('record_episode_completion',{p_series_id:runtime.activeSeries?.id,p_episode_id:String(runtime.activeEpisode||1)});await economy()}catch(e){console.warn(e)}});document.addEventListener('click',async ev=>{if(!cloud.session?.user)return;const daily=ev.target.closest('#claimDaily');if(daily){ev.preventDefault();ev.stopImmediatePropagation();try{const{error}=await cloud.client.rpc('claim_daily_reward');if(error)throw error;await sync();say('Recompensa diaria sincronizada')}catch(e){say('No se pudo reclamar la recompensa')}return}const task=ev.target.closest('[data-task]');if(task&&task.dataset.task!=='ad'){ev.preventDefault();ev.stopImmediatePropagation();try{const fn=task.dataset.task==='library'?'claim_library_reward':'claim_three_episode_reward';const args=task.dataset.task==='library'?{p_series_id:(state.library||[])[0]||'saved'}:{};const{error}=await cloud.client.rpc(fn,args);if(error)throw error;await sync();say('Recompensa sincronizada')}catch(e){say('Misión pendiente o ya reclamada')}return}const uc=ev.target.closest('#unlockCoins'),up=ev.target.closest('#useFreePass');if((uc||up)&&typeof runtime!=='undefined'&&runtime.pendingUnlock){ev.preventDefault();ev.stopImmediatePropagation();const p={...runtime.pendingUnlock};try{const fn=uc?'unlock_episode_with_coins':'unlock_episode_with_pass';const{error}=await cloud.client.rpc(fn,{p_series_id:p.id,p_episode:p.ep});if(error)throw error;await sync();typeof unlockEpisode==='function'&&unlockEpisode(p.id,p.ep);runtime.pendingUnlock=null;typeof closeLayer==='function'&&closeLayer('unlockModal',{restoreFocus:false});render();typeof playSeries==='function'&&playSeries(p.id,p.ep)}catch(e){say('No se pudo desbloquear el episodio')}return}if(ev.target.closest('#simulateCoinPurchase')){ev.preventDefault();ev.stopImmediatePropagation();say('Recargas locales desactivadas en modo nube')}},true)}
async function init(){style();card();try{await lib();cloud.client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const{data,error}=await cloud.client.auth.getSession();if(error)throw error;cloud.session=data.session;cloud.ready=true;authUI();hooks();cloud.client.auth.onAuthStateChange((_e,s)=>{cloud.session=s;authUI();if(s?.user)setTimeout(()=>sync(true),0)});if(cloud.session?.user)await sync(true)}catch(e){console.error(e);status('Supabase no está disponible. ZORYVO continúa en modo local.','err')}}
window.ZoryvoCloud={cloud,sync,push};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();